language: javascript
install: true
script:
    - zip -r ckeditor-ruler.zip ./
deploy:
    provider: releases
    api_key: "85fe91b2929542b1d1d2deb04b62429ddfe1be56"
    file: "ckeditor-ruler.zip"
    skip_cleanup: true
